name: Samlingsärende 🗂️
description: Samlingsärende för att organisera relaterade ärenden.
title: "[Samlingsärende]: "
labels:
  - samlingsärende
body:
  - type: textarea
    id: intro
    attributes:
      label: Info
      description: Förifylld text som beskriver detta ärende.
      value: >
        > Det här är ett samlingsärende.
        > Ärendet uppdateras löpande.

        > Deluppgifter ska skapas som GitHub sub-issues kopplade till detta ärende.

        _NOTE: Diskussioner om specifika ärenden görs i respektive ärende._
  - type: textarea
    id: dod
    attributes:
      label: Definition of Done (DoD)
      description: Kriterier som måste uppfyllas för att uppgiften ska anses vara klar.
      placeholder: |
        - Enhetstester är skrivna och godkända
        - Kodgranskning är genomförd
        - Dokumentation är uppdaterad
      value: >
        - När alla sub-issues är stängda
    validations:
      required: true
